@URL = http://localhost:3000


### Authenticate and get token
# @name login
POST {{URL}}/auth/login
Content-Type: application/json

{
  "username": "Alice",
  "password": "topsecret"
}

### Get specific user information
GET {{URL}}/auth/me HTTP/1.1
Authorization: Bearer {{login.response.body.$.accessToken}}